sudo: false

dist: bionic

language: node_js
node_js:
  - '12'

addons:
  apt:
    packages:
      - libgconf-2-4
  chrome: stable

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn --frozen-lockfile --non-interactive --no-progress

script:
  # lint
  - yarn demo:lint:check
  - yarn prettier:check
  # tests
  - yarn lib:test:ci
  # build
  - yarn lib:build:prod
  - yarn demo:build:prod --progress=false --base-href "https://zakhenry.github.io/wireframe-svg/"
  - sed -i 's/<base href="https:\/\/zakhenry.github.io\/wireframe-svg\/">/<base href="\/">/g' dist/wireframe-svg-demo/index.html
  - cd ./dist/wireframe-svg-demo
  - nohup http-server-spa . index.html 4765 &
  - cd ../..
  - sleep 5
  - sed -i 's/<base href="\/">/<base href="https:\/\/zakhenry.github.io\/wireframe-svg\/">/g' dist/wireframe-svg-demo/index.html

  - rm dist/wireframe-svg/README.md && cp README.md dist/wireframe-svg
  - cp LICENSE dist/wireframe-svg

deploy:
  - provider: script
    skip_cleanup: true
    script: yarn semantic-release
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: dist/wireframe-svg
    on:
      branch: master
